global ru.vsu.extinguishfiredecision.Result resultObj;
import java.util.List
import  ru.vsu.extinguishfiredecision.model.Fire;
import ru.vsu.extinguishfiredecision.FireExtinguisherTypes;

rule "Fire-extinguishers-type-b  rule"
when
    Fire(getType()=='TYPE_B')
then
    resultObj.setFireExtinguisher(List.of(FireExtinguisherTypes.DRY_POWDER,FireExtinguisherTypes.FOAM,FireExtinguisherTypes.CO2));
 end