global ru.vsu.extinguishfiredecision.Result resultObj;
import java.util.List
import  ru.vsu.extinguishfiredecision.model.Fire;
import ru.vsu.extinguishfiredecision.FireExtinguisherTypes;

rule "Fire-extinguishers-type-a rule"
when
    Fire(getType()=='TYPE_A')
then
    resultObj.setFireExtinguisher(List.of(FireExtinguisherTypes.WATER,FireExtinguisherTypes.DRY_POWDER,FireExtinguisherTypes.FOAM,FireExtinguisherTypes.WET_CHEMICAL));
 end