global ru.vsu.extinguishfiredecision.Result resultObj;
import java.util.List;
import  ru.vsu.extinguishfiredecision.model.Fire;
import  ru.vsu.extinguishfiredecision.FireTypes;
import ru.vsu.extinguishfiredecision.FireExtinguisherTypes;

rule "Fire-extinguishers-type-a rule"
  when
    Fire(getType() == FireTypes.TYPE_A)
  then
    resultObj.setFireExtinguisher(List.of(FireExtinguisherTypes.WATER,FireExtinguisherTypes.DRY_POWDER,FireExtinguisherTypes.FOAM,FireExtinguisherTypes.WET_CHEMICAL));
end

rule "Fire-extinguishers-type-b  rule"
  when
    Fire(getType()==FireTypes.TYPE_B)
  then
    resultObj.setFireExtinguisher(List.of(FireExtinguisherTypes.DRY_POWDER,FireExtinguisherTypes.FOAM,FireExtinguisherTypes.CO2));
end

rule "Fire-extinguishers-type-c rule"
  when
    Fire(getType()==FireTypes.TYPE_C)
  then
    resultObj.setFireExtinguisher(List.of(FireExtinguisherTypes.DRY_POWDER,FireExtinguisherTypes.CO2));
end


rule "Fire-extinguishers-type-d rule"
  when
    Fire(getType() == FireTypes.TYPE_D)
  then
    resultObj.setFireExtinguisher(List.of(FireExtinguisherTypes.SPECIAL_POWDER_INJECTION));
end